#
# Copyright 2019 Amazon.com, Inc. or its affiliates.  All Rights Reserved.
# These materials are licensed under the Amazon Software License in connection with the Alexa Gadgets Program.
# The Agreement is available at https://aws.amazon.com/asl/.
# See the Agreement for the specific terms and conditions of the Agreement.
# Capitalized terms not defined in this file have the meanings given to them in the Agreement.
#
version: 0.0
os: linux
files:
  - source: /device
    destination: /home/smart-mirror/
  - source: /device/systemd
    destination: /etc/systemd/system/
hooks:
  BeforeInstall:
    - location: device/beforeInstall.sh
      timeout: 600
      runas: root    
  AfterInstall:
    - location: device/afterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: device/start.sh
      timeout: 300
      runas: root
